import { Request, Response } from 'express';
import { CompanyController } from '../../src/controllers/companyController';

import { prisma } from '../../src/database/prismaClient';

function createMockResponse(): Response {
  const res = {
    status: jest.fn().mockReturnThis(),
    json: jest.fn(),
    send: jest.fn(),
  };
  return res as unknown as Response;
}

describe('CompanyController (static)', () => {
  beforeEach(async () => {
    jest.clearAllMocks();

    await prisma.userRole.deleteMany();
    await prisma.companyDomain.deleteMany();
    await prisma.rolePermission.deleteMany();
    await prisma.session.deleteMany();
    await prisma.user.deleteMany();
    await prisma.role.deleteMany();
    await prisma.company.deleteMany();
    await prisma.domain.deleteMany();
    await prisma.permission.deleteMany();
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  describe('createCompany', () => {
    it('should create a company and return 201 status', async () => {
      const req = {
        body: {
          name: 'New Company',
          description: 'New Desc',
          isActive: true,
        },
      } as unknown as Request;
      const res = createMockResponse();

      await CompanyController.createCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(201);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
          // The ID is generated by Prisma
          name: 'New Company',
        })
      );
    });

    it('should return 400 for invalid validation data', async () => {
      const req = { body: { name: 123 } } as unknown as Request;
      const res = createMockResponse();

      await CompanyController.createCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
          message: 'Invalid validation data',
          errors: expect.any(Array),
        })
      );
    });

    it('should return 409 if company name already exists', async () => {
      const req = {
        body: {
          name: 'Company',
          description: 'Error test',
          isActive: true,
        },
      } as unknown as Request;
      const res = createMockResponse();

      await prisma.company.create({
        data: {
          name: req.body.name,
          description: 'Existing Desc',
          isActive: true,
        },
      });

      await CompanyController.createCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(500);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({
          message: 'Company with this name already exists.',
        })
      );
    });
  });

  describe('getCompanyById', () => {
    it('should return 200 and company if found', async () => {
      const res = createMockResponse();
      const company = await prisma.company.create({
        data: {
          name: 'Test Company',
          description: 'Test Description',
          isActive: true,
        },
      });
      const req = { params: { id: company.id } } as unknown as Request;
      await CompanyController.getCompanyById(req, res);

      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({ id: company.id })
      );
    });

    it('should return 404 if not found', async () => {
      const req = { params: { id: '404' } } as unknown as Request;
      const res = createMockResponse();

      await CompanyController.getCompanyById(req, res);

      expect(res.status).toHaveBeenCalledWith(404);
      expect(res.json).toHaveBeenCalledWith({ message: 'Company not found' });
    });
  });

  describe('getAllCompanies', () => {
    it('should return all companies', async () => {
      const req = {} as Request;
      const res = createMockResponse();
      const companiesData = [
        {
          name: 'Test Company 1',
          description: 'Desc 1',
          isActive: true,
        },
        {
          name: 'Test Company 2',
          description: 'Desc 2',
          isActive: false,
        },
      ];

      await prisma.company.createMany({
        data: companiesData,
      });

      await CompanyController.getAllCompanies(req, res);

      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith(
        expect.arrayContaining([
          expect.objectContaining({ name: 'Test Company 1' }),
          expect.objectContaining({ name: 'Test Company 2' }),
        ])
      );
      expect((res.json as jest.Mock).mock.calls[0][0].length).toBe(2);
    });

    it('should return empty array and 200 status if no companies', async () => {
      const req = {} as Request;
      const res = createMockResponse();

      await CompanyController.getAllCompanies(req, res);

      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith([]);
    });
  });

  describe('updateCompany', () => {
    it('should update and return 200', async () => {
      const res = createMockResponse();
      const company = await prisma.company.create({
        data: {
          name: 'Old Company',
          description: 'Old Description',
          isActive: true,
        },
      });
      const req = {
        params: { id: company.id },
        body: { name: 'Updated' },
      } as unknown as Request;

      await CompanyController.updateCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.json).toHaveBeenCalledWith(
        expect.objectContaining({ name: 'Updated' })
      );
    });

    it('should return 404 if not found', async () => {
      const req = {
        params: { id: '1' },
        body: { name: 'Updated' },
      } as unknown as Request;
      const res = createMockResponse();

      await CompanyController.updateCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(404);
    });
  });

  describe('deleteCompany', () => {
    it('should delete and return 204', async () => {
      const res = createMockResponse();
      const company = await prisma.company.create({
        data: {
          name: 'Test Company',
          description: 'Test Description',
          isActive: true,
        },
      });
      const req = { params: { id: company.id } } as unknown as Request;

      await CompanyController.deleteCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(204);
      expect(res.send).toHaveBeenCalled();
    });

    it('should return 404 if not found', async () => {
      const req = { params: { id: '404' } } as unknown as Request;
      const res = createMockResponse();

      await CompanyController.deleteCompany(req, res);

      expect(res.status).toHaveBeenCalledWith(404);
    });
  });
});
