openapi: 3.0.0
info:
  title: Factory Backend API
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Development server

paths:
  /api/v1/auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      description: Authenticates a user with email/password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
        '400':
          description: Invalid data

  /api/v1/auth/logout:
    post:
      tags:
        - Authentication
      summary: User logout
      description: |
        Logs out the user by invalidating the token and session.
        Requires a valid JWT token in the Authorization header with the format: "Bearer <token>"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
              example:
                message: 'Logout successful'
        '400':
          description: Missing or malformed Authorization header
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponse'
              example:
                message: 'Missing token'
        '401':
          description: Authentication failed - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponse'
              examples:
                invalid_token:
                  summary: Invalid token
                  value:
                    message: 'Invalid token'
                auth_required:
                  summary: Authentication required
                  value:
                    message: 'Authentication required'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: 'Internal server error'

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          minLength: 6
          description: Password (minimum 6 characters)

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Authentication JWT token
        user:
          $ref: '#/components/schemas/User'

    LogoutResponse:
      type: object
      properties:
        message:
          type: string
          example: 'Logout successful'

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur descriptif

    AuthErrorResponse:
      type: object
      properties:
        message:
          type: string
          enum:
            - 'Authentication required'
            - 'Invalid token'
            - 'Missing token'
          description: Message d'erreur d'authentification

    User:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the user
        email:
          type: string
          format: email
          description: User's email address
        firstName:
          type: string
          nullable: true
          description: User's first name
        lastName:
          type: string
          nullable: true
          description: User's last name

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
