/api/v1/domain:
  post:
    tags:
      - Domain
    summary: Create a new domain
    description: |
      Creates a new domain.
      Requires appropriate administrative permissions.
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateDomainRequest'
    responses:
      '201':
        description: Domain created successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainResponse'
      '400':
        description: Invalid request data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

  get:
    tags:
      - Domain
    summary: Retrieve all domains
    description: |
      Retrieves all available domains.
      Access restrictions apply based on the user's role.
    security:
      - bearerAuth: []
    responses:
      '200':
        description: Domains retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainListResponse'
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/api/v1/domain/{id}:
  get:
    tags:
      - Domain
    summary: Retrieve a domain by ID
    description: |
      Retrieves a specific domain by its ID.
      Requires appropriate access permissions.
    security:
      - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Domain ID
    responses:
      '200':
        description: Domain retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainResponse'
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions or access denied
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '404':
        description: Domain not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

  put:
    tags:
      - Domain
    summary: Update a domain
    description: |
      Updates an existing domain.
      Requires appropriate administrative permissions.
    security:
      - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Domain ID
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateDomainRequest'
    responses:
      '200':
        description: Domain updated successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainResponse'
      '400':
        description: Invalid request data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions or access denied
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '404':
        description: Domain not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

  delete:
    tags:
      - Domain
    summary: Delete a domain
    description: |
      Deletes a domain.
      Requires appropriate administrative permissions.
    security:
      - bearerAuth: []
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Domain ID
    responses:
      '204':
        description: Domain deleted successfully
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions or access denied
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '404':
        description: Domain not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/api/v1/domain/company-domain:
  post:
    tags:
      - Domain
    summary: Create a company-domain association
    description: |
      Creates an association between a company and a domain.
      Requires appropriate administrative permissions.
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateCompanyDomainRequest'
    responses:
      '201':
        description: Association created successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyDomainResponse'
      '400':
        description: Invalid request data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/api/v1/domain/company/{companyId}/domain/{domainId}:
  delete:
    tags:
      - Domain
    summary: Delete a company-domain association
    description: |
      Deletes an association between a company and a domain.
      Requires appropriate administrative permissions.
    security:
      - bearerAuth: []
    parameters:
      - name: companyId
        in: path
        required: true
        schema:
          type: string
        description: Company ID
      - name: domainId
        in: path
        required: true
        schema:
          type: string
        description: Domain ID
    responses:
      '204':
        description: Association deleted successfully
      '401':
        description: Authentication required
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthErrorResponse'
      '403':
        description: Insufficient permissions or access denied
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '404':
        description: Association not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
